languages = {
"Java":"Java,#Java",
"C":"#C",
"C++":"CplusPlus, #C++, #Cpp",
"Objective-C":"Objective-C,#Objective-C",
"CSharp":"CSharp,#CSharp",
"Python":"Python,#Python",
"Javascript":"Javascript,#Javascript",
"Visual Basic .NET":"Visual Basic .NET,#Visual Basic .NET",
"PHP":"#PHP",
"Visual Basic":"Visual Basic,#Visual Basic",
"Perl":"Perl,#Perl",
"R":"#R",
"Delphi":"Delphi,#Delphi",
"Object Pascal":"Object Pascal,#Object Pascal",
"Matlab":"Matlab,#Matlab",
"Ruby":"Ruby,#Ruby",
"Cobol":"Cobol,#Cobol",
"Pl":"Pl,#Pl",
"Sql":"Sql,#Sql",
"Swift":"Swift,#Swift",
"Pascal":"Pascal,#Pascal",
"Abap":"Abap",
}

lang = [
"#Java",
"#C",
"#Objective-C",
"#CSharp",
"#Python",
"#Javascript",
"#Visual Basic .NET",
"#PHP",
"#Visual Basic",
"#Perl",
"#R",
"#Delphi",
"#Object Pascal",
"#Matlab",
"#Ruby",
"#Cobol",
"#Pl",
"#Sql",
"#Swift",
"#Pascal",
"#Abap",
"Java",
"Cplusplus",
"Obj-c",
"CSharp",
"Python",
"Javascript",
"Visual Basic .NET",
"Visual Basic",
"Delphi",
"Object Pascal",
"Matlab",
"Cobol",
"Sql",
"Abap"
]